let ss = document.querySelector(".sss")
ss.onclick = () =>{
    alert("Rahmat baroi obuna")
} 
let button = document.querySelector("#ip")
let cnt = 0
let div =  document.querySelector(".div")
let a1 = document.querySelector(".a1")
let a2 = document.querySelector(".a2")
let a3 = document.querySelector(".a3")
let a4 = document.querySelector(".a4")
let h3 = document.querySelector(".h3")
let h4 = document.querySelector(".h4")
let h5 = document.querySelector(".h5")
let h2 = document.querySelector(".h2")
let p2 = document.querySelector(".p2")
let p3 = document.querySelector(".p3")
let p4 = document.querySelector(".p4")
let p5 = document.querySelector(".p5")
let vt1 = document.querySelector(".vt1")
let x = document.querySelector(".x")
let ml1 = document.querySelector(".ml1")
let vn = document.querySelector(".vn")
let dd1 = document.querySelector(".dd1")
let kp1 = document.querySelector(".kp1")
let kp2 = document.querySelector(".kp2")
let kp3 = document.querySelector(".kp3")
let n1 = document.querySelector(".n1")
let n2 = document.querySelector(".n2")
let n3 = document.querySelector(".n3")
let n4 = document.querySelector(".n4")
let img = document.querySelector(".img2")
let ss1 = document.querySelector(".ss11")
let s2 = document.querySelector(".s2")
let s3 = document.querySelector(".s3")
let s4 = document.querySelector(".s4")
let o1 = document.querySelector(".o1")
let o2 = document.querySelector(".o2")
let o3 = document.querySelector(".o3")
let o4 = document.querySelector(".o4")
let x1 = document.querySelector(".x1")
let x2 = document.querySelector(".x2")
let x3 = document.querySelector(".x3")
let x4 = document.querySelector(".x4")
let vv1 = document.querySelector(".vv1")
let vv2 = document.querySelector(".vv2")
let vv3 = document.querySelector(".vv3")
let vv4 = document.querySelector(".vv4")
let bn1 = document.querySelector(".hh1")
let bn2 = document.querySelector(".hh2")
let bn3 = document.querySelector(".hh3")
let bn4 = document.querySelector(".hh4")
let f2 = document.querySelector(".f2")
let f3 = document.querySelector(".f3")
let f4 = document.querySelector(".f4")
let f5 = document.querySelector(".f5")
let cs1 = document.querySelector(".cs1")
let cs2 = document.querySelector(".cs2")
let cs3 = document.querySelector(".cs3")
let l1 = document.querySelector(".l1")
let l2 = document.querySelector(".l2")
let cs4 = document.querySelector(".cs4")
let jin = document.querySelector(".jin")
let ml2 = document.querySelector(".ml2")
let bj1 = document.querySelector(".bj1")
let g1 = document.querySelector(".g1")
let g2 = document.querySelector(".g2")
let dib1 = document.querySelector(".dib1")
let s22 = document.querySelector(".s22")
let s23 = document.querySelector(".s23")
let s24 = document.querySelector(".s24")
let s25 = document.querySelector(".s25")
let s26 = document.querySelector(".s26")
let b2 = document.querySelector(".bn1")
let span1 = document.querySelector(".span1")
let bl1 = document.querySelector(".bl1")
let text1 = document.querySelector(".text1")
function sum(){
    const audio = new Audio()
    audio.src = "live_chat_001_38569.mp3"
    audio.play()
}
button.onclick = () =>{
    cnt++;
    if(cnt%2!=0){
        sum()
        div.style.backgroundColor = "transparent";
        div.style.borderBottom = "0.1px solid #E2E8F0" 
        div.style.backdropFilter = "blur(7px)"
        a1.style.color = "#ddd"
        a2.style.color = "#ddd"
        a3.style.color = "#ddd"
        a4.style.color = "#ddd"
        document.body.style.backgroundColor = "#000D29"
        h3.style.color="white"
        p2.style.color = "white"
        vt1.style.color = 'white'
        x.style.backgroundColor = "#000D29"
        ml1.style.backgroundColor = "#000D29"
        h2.style.color = "white"
        h4.style.color = "white"
        h5.style.color = "white"
        p3.style.color = "white"
        p4.style.color = "white"
        p5.style.color = "white"
        vn.style.color = "white" 
        dd1.style.backgroundColor = "#051944"  
        dd1.style.boxShadow = "0px 0px 10px white"
        text1.style.backgroundColor = "#051944"  
        kp1.style.color = "white"
        kp2.style.color = "white"
        kp3.style.color = "white"
        n1.style.backgroundColor = "#051944"  
        n1.style.boxShadow = "0px 0px 10px white"
        n2.style.color = "white"
        n3.style.color = "white"
        n4.style.color = "white"
        ss1.style.backgroundColor = "#051944"  
        ss1.style.boxShadow = "0px 0px 10px white"
        s2.style.color = "white"
        s3.style.color = "white"
        s4.style.color = "white"
        o1.style.backgroundColor = "#051944"  
        o1.style.boxShadow = "0px 0px 10px white"
        o2.style.color = "white"
        o3.style.color = "white"
        o4.style.color = "white"
        x1.style.backgroundColor = "#051944"  
        x1.style.boxShadow = "0px 0px 10px white"
        x2.style.color = "white"
        x3.style.color = "white"
        x4.style.color = "white"
        vv1.style.backgroundColor = "#051944"  
        vv1.style.boxShadow = "0px 0px 10px white"
        vv2.style.color = "white"
        vv3.style.color = "white"
        vv4.style.color = "white"
        f2.style.backgroundColor = "#051944"  
        f2.style.boxShadow = "0px 0px 10px white"
        f3.style.color = "white"
        f4.style.color = "white"
        f5.style.color = "white"
        bn1.style.backgroundColor = "#051944"  
        bn1.style.boxShadow = "0px 0px 10px white"
        bn2.style.color = "white"
        bn3.style.color = "white"
        bn4.style.color = "white"
        cs1.style.backgroundColor = "#051944"  
        cs1.style.boxShadow = "0px 0px 10px white"
        cs2.style.color = "white"
        cs3.style.color = "white"
        cs4.style.color = "white"
        jin.style.backgroundColor = "#051944"
        jin.style.color
         = "white"
        ml2.style.boxShadow = "0px 0px 10px white"
        ml2.style.backgroundColor = "#051944"
        l2.style.backgroundColor = "#051944"
        l1.style.boxShadow = "0px 0px 10px white"
        l2.style.color = "white"
        bj1.style.color = "white"
        bj1.classList.add("bj1")
        l1.style.backgroundColor = "#051944"
        g1.style.backgroundColor = "#051944"
        g1.style.boxShadow = "0px 0px 10px white"
        dib1.style.backgroundColor = "#051944"
        g2.style.color = "white"
        dib1.style.color = "white"
        dib1.style.boxShadow = "0px 0px 10px white"
        s22.style.color = "white"
        s23.style.color = "white"
        s24.style.color = "white"
        s25.style.color = "white"
        s26.style.color = "white"
        b2.style.color = "white"
        span1.style.color = "white"
        bl1.classList.add("bl1")
    }
    else{
        sum()
        text1.style.backgroundColor = "white"
        document.body.style.backgroundColor = "white"
        div.style.backgroundColor = "#E2E7ECCC"
        a1.style.color = "#02011cb3"
        a2.style.color = "#02011cb3"
        a3.style.color = "#02011cb3"
        a4.style.color = "#02011cb3"
        div.style.borderBottom = "1px solid #E2E8F0" 
        h3.style.color = "#0F172A"
        p2.style.color = "#0F172A"
        vt1.style.color = "#0F172A"
        x.style.backgroundColor = "white"
        ml1.style.backgroundColor = "white"
        h2.style.color = "black"
        h4.style.color = "black"
        h5.style.color = "black"
        p3.style.color = "black"
        p4.style.color = "black"
        p5.style.color = "black"
        vn.style.color = "black"
        dd1.style.backgroundColor = "white"
        n1.style.backgroundColor = "white"
        n2.style.color = "black"
        n3.style.color = "black"
        n4.style.color = "black"
        cs1.style.backgroundColor = "white"
        cs2.style.color = "black"
        cs3.style.color = "black"
        cs4.style.color = "black"
        dd1.style.backgroundColor = "white"
        kp1.style.color = "black"
        kp2.style.color = "black"
        kp3.style.color = "black"
        ss1.style.backgroundColor = "white"
        s2.style.color = "black"
        s3.style.color = "black"
        s4.style.color = "black"    
        o1.style.backgroundColor = "white"
        o2.style.color = "black"
        o3.style.color = "black"
        o4.style.color = "black"    
        x1.style.backgroundColor = "white"
        x2.style.color = "black"
        x3.style.color = "black"
        x4.style.color = "black"  
        bn1.style.backgroundColor = "white"
        bn2.style.color = "black"
        bn3.style.color = "black"
        bn4.style.color = "black"
        s22.style.color = "black"  
        s23.style.color = "black"  
        s24.style.color = "black"  
        s25.style.color = "black"  
        s26.style.color = "black"  
        b2.style.color = "black"  
        span1.style.color = "black"  
        vv1.style.backgroundColor = "white"
        vv2.style.color = "black"
        vv3.style.color = "black"
        vv4.style.color = "black"  
        f2.style.backgroundColor = "white"
        f3.style.color = "black"
        f4.style.color = "black"
        f5.style.color = "black" 
        jin.style.backgroundColor = "white"
        jin.style.color = "black"
        bj1.style.color = "black"
        l1.style.backgroundColor = "white"
        l2.style.color = "black"
        l2.style.backgroundColor = "white"
        ml2.style.backgroundColor = "white"
        bj1.style.color = "black"
        g1.style.backgroundColor = "white"
        dib1.style.backgroundColor = "white"
        g2.style.color = "black"
        dib1.style.color = "white"
    }  
}